apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- argocd-ingress.yaml
- argocd.yaml
- bmc-reverse-proxy.yaml
- cert-manager.yaml
- coil.yaml
- customer-egress.yaml
- elastic.yaml
- external-dns.yaml
- ingress.yaml
- local-pv-provisioner.yaml
- logging.yaml
- metallb.yaml
- moco.yaml
- monitoring.yaml
- namespaces.yaml
- neco-admission.yaml
- network-policy.yaml
- prometheus-adapter.yaml
- pvc-autoresizer.yaml
- rook.yaml
- sandbox.yaml
- sealed-secrets.yaml
- secrets.yaml
- team-management.yaml
- teleport.yaml
- topolvm.yaml
- unbound.yaml
