ArgoCDApplicationValidator:
    rules:
      - repository: https://github.com/cybozu-private/ept-apps.git
        projects:
          - ept
          - tenant-app-of-apps
      - repository: https://github.com/cybozu-private/maneki-apps.git
        projects:
          - maneki
          - tenant-app-of-apps
      - repository: https://github.com/cybozu-go/neco-apps.git
        projects:
          - default
      - repository: https://github.com/cybozu-private/neco-apps-secret.git
        projects:
          - default
