apiVersion: apps/v1
kind: Deployment
metadata:
  name: neco-admission
  namespace: kube-system
  labels:
    app.kubernetes.io/name: neco-admission
  annotations:
    prometheus.io/path: "/metrics"
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: neco-admission
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: neco-admission
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - neco-admission
            topologyKey: cke.cybozu.com/rack
      containers:
      - name: neco-admission
        args:
        - --cert-dir=/certs
        - --httpproxy-default-class=forest
        - --zap-stacktrace-level=panic
        - --valid-image-prefix=quay.io/cybozu/
        - --valid-image-prefix=quay.io/topolvm/
        - --valid-image-prefix=ghcr.io/cybozu/
        - --valid-image-prefix=ghcr.io/cybozu-go/
        - --valid-image-prefix=ghcr.io/cybozu-private/
        - --valid-image-prefix=docker.elastic.co/
        - --valid-image-prefix=quay.io/gravitational/teleport-ent
        - --valid-image-prefix=datadog/agent,docker.io/datadog/agent
        # TODO: remove this after we build our own images for Rook
        - --valid-image-prefix=k8s.gcr.io/sig-storage/,quay.io/cephcsi/
        # TODO: remove this after https://github.com/cybozu-go/neco/issues/1408
        - --valid-image-prefix=quay.io/integreatly/grafana_plugins_init
        image: quay.io/cybozu/neco-admission
        resources:
          requests:
            cpu: 100m
            memory: 30Mi
        volumeMounts:
          - name: certs
            mountPath: /certs
          - name: config
            mountPath: /etc/neco-admission
        ports:
          - name: metrics
            containerPort: 8080
          - name: health
            containerPort: 8081
          - name: webhook
            containerPort: 9443
        readinessProbe:
          httpGet:
            path: /readyz
            port: health
            scheme: HTTP
        livenessProbe:
          httpGet:
            path: /healthz
            port: health
            scheme: HTTP
        lifecycle:
            preStop:
              exec:
                command: ["sleep", "5"]
      terminationGracePeriodSeconds: 10
      volumes:
        - name: certs
          secret:
            secretName: neco-admission-webhook
        - name: config
          configMap:
            name: neco-admission-config
---
apiVersion: v1
kind: Service
metadata:
  name: neco-admission
  namespace: kube-system
spec:
  selector:
    app.kubernetes.io/name: neco-admission
  ports:
  - protocol: TCP
    port: 443
    targetPort: webhook
