apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
namePrefix: victoriametrics-
resources:
  - ../upstream/rbac
patches:
- path: service_account_patch.yaml
  target:
    name: leader-election-rolebinding
- path: service_account_patch.yaml
  target:
    name: manager-rolebinding
patchesStrategicMerge:
- psp_clusterrole_patch.yaml
