apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - upstream/cert-manager.yaml
  - rbac.yaml
patches:
  - crd.yaml
  - deployment.yaml
  - mutatingwebhookconfiguration.yaml
  - validatingwebhookconfiguration.yaml
images:
  - name: quay.io/cybozu/cert-manager
    newTag: 1.0.4.1
