apiVersion: apps/v1
kind: Deployment
metadata:
  name: table-manager
  namespace: logging
spec:
  minReadySeconds: 10
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: table-manager
  template:
    metadata:
      annotations:
        config_hash: 7d24e5f431bbd1a56f45e7a0b8a793eb
      labels:
        name: table-manager
    spec:
      containers:
      - args:
        - -bigtable.backoff-on-ratelimits=true
        - -bigtable.grpc-client-rate-limit=5
        - -bigtable.grpc-client-rate-limit-burst=5
        - -bigtable.table-cache.enabled=true
        - -config.expand-env=true
        - -config.file=/etc/loki/config/config.yaml
        - -limits.per-user-override-config=/etc/loki/overrides/overrides.yaml
        - -target=table-manager
        image: quay.io/cybozu/loki:2.1.0.1
        imagePullPolicy: IfNotPresent
        name: table-manager
        ports:
        - containerPort: 3100
          name: http-metrics
        - containerPort: 9095
          name: grpc
        readinessProbe:
          httpGet:
            path: /ready
            port: 3100
          initialDelaySeconds: 15
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - mountPath: /etc/loki/config
          name: loki
      volumes:
      - configMap:
          name: loki
        name: loki
