apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - grafana-operator/httpproxy.yaml
  - mackerel-agent.yaml
patchesStrategicMerge:
  - grafana-operator/grafana.yaml
  - pushgateway/httpproxy.yaml
  - ingress-health/httpproxy.yaml
  - victoriametrics/vmsingle-smallset.yaml
  - victoriametrics/vmcluster-largeset.yaml
configMapGenerator:
  - name: vmalertmanager
    behavior: merge
    files:
      - victoriametrics/env.template
