apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - grafana-operator
  - machines-endpoints/cronjob.yaml
  - machines-endpoints/role.yaml
  - machines-endpoints/rolebinding.yaml
  - machines-endpoints/serviceaccount.yaml
  - machines-endpoints/pod-security-policy.yaml
  - kube-state-metrics/deployment.yaml
  - kube-state-metrics/cluster-role.yaml
  - kube-state-metrics/cluster-role-binding.yaml
  - kube-state-metrics/service.yaml
  - kube-state-metrics/service-account.yaml
  - pushgateway/deployment.yaml
  - pushgateway/httpproxy.yaml
  - pushgateway/service.yaml
  - ingress-health/deployment.yaml
  - ingress-health/httpproxy.yaml
  - ingress-health/service.yaml
  - victoriametrics
patchesStrategicMerge:
  - patch-kube-state-metrics.yaml
images:
  - name: quay.io/cybozu/pushgateway
    newTag: 1.4.0.1
  - name: k8s.gcr.io/kube-state-metrics/kube-state-metrics
    newName: quay.io/cybozu/kube-state-metrics
    newTag: 2.0.0-beta.1
  - name: quay.io/integreatly/grafana-operator
    newName: quay.io/cybozu/grafana-operator
    newTag: 3.8.1.1
